# Generated by Django 5.2.5 on 2025-08-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐ 1'), (2, '⭐ 2'), (3, '⭐ 3'), (4, '⭐ 4'), (5, '⭐ 5')]),
        ),
    ]
